- TensorFlow is a Framework from Google,that is useful to develop Machine Learning and Deep Learning Program.
- TensorFlow is open source.
- Keras is a high-level Neural Networks library written in Python.
- Cognitive Toolkit(CNTK) or Theano is deep learning framework developed by Microsoft.

#### Install keras and tensorflow

In [1]:
import tensorflow as tf

2024-12-05 09:00:30.666406: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
print(tf.__version__)

2.16.2


# FUNDAMENTALS OF TENSORFLOW 

- In the word TensorFlow,'tensor' represents a multidimensional array and 'flow' represents a graph of operations.
    

In [3]:

a =  10 
b = 20 
c = tf.add(a,b)
print(c)

tf.Tensor(30, shape=(), dtype=int32)


# PROPERTIES OF A TENSORFLOW

- Every tensor will have 3 properties:
    - A unique label (name)
    - A dimension (shape)
    - A data type (dtype)

# TYPES OF TENSORS

- 4 types of tensors:
  -  tf.constant
  -  tf.Variable
  -  tf.placeholder
  -  tf.SparseTensor

# CONSTANT TENSORS

tf.constant(value,dtype,name="")
- tf.string
- tf.int16
- tf.float32

In [4]:
import tensorflow as tf 
print(tf.constant(10))
print(tf.constant(10,dtype=tf.int16))
print(tf.constant(10,tf.int16,name="my value"))
print(tf.constant(10.50,tf.float32))
print(tf.constant('my name is prodip'))

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int16)
tf.Tensor(10, shape=(), dtype=int16)
tf.Tensor(10.5, shape=(), dtype=float32)
tf.Tensor(b'my name is prodip', shape=(), dtype=string)


# VARIABLE TENSOR

- tf.variable(value,dtype,name="")

In [5]:
v1 = tf.Variable(10)
print(v1)
v2 = v1.assign(26)
print(v2)
# change the value v1 to new variable value
new_var = 100
v3 = v1.assign(new_var)
print(v3)
# store string value 
v1 = tf.Variable("Hello")
print(v1)
# change Hello to hello man
v2 = v1.assign('hello man')
print(v2) 

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=26>
<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=100>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello'>
<tf.Variable 'UnreadVariable' shape=() dtype=string, numpy=b'hello man'>


# CREATING TENSOR WITH ARRAYS

In [6]:
# 1D array 
arr1 = tf.constant([10,20,30,40])
print(arr1)

tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)


In [7]:
# 2D array (2 rows and 3 columns)
arr2 = tf.constant([[10,20,25],[30,40,45]])
print(arr2)

tf.Tensor(
[[10 20 25]
 [30 40 45]], shape=(2, 3), dtype=int32)


In [8]:
# 3D array (2D with 2 rows and 3 columns)
arr3 = tf.Variable([[[10,20,25],[30,40,45]],[[10,20,25],[30,40,45]]])
print(arr3)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 20, 25],
        [30, 40, 45]],

       [[10, 20, 25],
        [30, 40, 45]]], dtype=int32)>


In [10]:
arr3.name

'Variable:0'

In [11]:
arr3.shape

TensorShape([2, 2, 3])

In [12]:
arr3.dtype # occupying 32 bits.sometimes the integers can also take 16 bits only. 

tf.int32

In [15]:
# addition of two numbers
a = tf.constant(10)
b = tf.constant(25)
c = tf.add(a,b)
print(c)
c1 = a + b
print('Value of c before running graph=',c1)

tf.Tensor(35, shape=(), dtype=int32)
Value of c before running graph= tf.Tensor(35, shape=(), dtype=int32)


# COMMON OPERATIONS IN TENSORFLOW

- tf.add(a,b)
- tf.substract(a,b)
- tf.multiply(a,b)
- tf.div(a,b)
- tf.pow(a,b)
- tf.exp(a)
- tf.sqrt(a)
- tf.matmul(a,b)

In [22]:
res = tf.pow(10.5,3)
print(res)

tf.Tensor(1157.625, shape=(), dtype=float32)


# KERAS

- Keras became part of TensorFlow Framework.
- There are 2 important places where Keras library is used
  - While creating Model for Artificial Neural Network
  - While creating Layers for Artificial Neural Network

- To summarise, Keras layer requires below minimum details to create a complete layer.
- Shape of the input data
- Number of neurons / units in the layer
- Initializers
- Regularizers
- Constraints
- Activations

#### The Keras Sequential Model

- While creating any type of Artificial Neural Network(ANN) ,the general way is to create the layers one by one and them sequentially so that the Network will be formed. 

In [25]:
from keras.models import Sequential

In [26]:
model = Sequential()

- Then we will create layers of the model and add them one at a time to the model.
- https://www.tutorialspoint.com/keras/keras_layers.htm
- https://www.tutorialspoint.com/keras/keras_models.htm

In [30]:
# Using Keras Desnse class , We can create Input Layer of the ANN
from keras.models import Sequential 
from keras.layers import Activation, Dense 
from keras import initializers 
from keras import regularizers 
from keras import constraints 

model = Sequential() 

model.add(Dense(32, input_shape=(16,), kernel_initializer = 'he_uniform', 
   kernel_regularizer = None, kernel_constraint = 'MaxNorm', activation = 'relu')) 
model.add(Dense(16, activation = 'relu')) 
model.add(Dense(8))

# LAYERS IN KERAS

- Dense Layer
- Dropout Layer
- Flatten Layer
- Pooling Layer
- Convolution Layer