In [25]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [27]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [28]:
# Vocanulary Size 
vocab_size = 10000

In [29]:
# one hot representation
onehot_repr = [one_hot(words,vocab_size) for words in sent]
onehot_repr

[[3015, 3836, 5472, 6520],
 [3015, 3836, 5472, 4686],
 [3015, 6696, 5472, 556],
 [1749, 3973, 5006, 5385, 2301],
 [1749, 3973, 5006, 5385, 3563],
 [6010, 3015, 8678, 5472, 8884],
 [7391, 5424, 8349, 5385]]

In [30]:
# Word embedding representation
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
import numpy as np
import pandas as pd

In [31]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 3015, 3836, 5472, 6520],
       [   0,    0,    0,    0, 3015, 3836, 5472, 4686],
       [   0,    0,    0,    0, 3015, 6696, 5472,  556],
       [   0,    0,    0, 1749, 3973, 5006, 5385, 2301],
       [   0,    0,    0, 1749, 3973, 5006, 5385, 3563],
       [   0,    0,    0, 6010, 3015, 8678, 5472, 8884],
       [   0,    0,    0,    0, 7391, 5424, 8349, 5385]], dtype=int32)

In [32]:
# Feature Representation
dim = 10

In [33]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [34]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step


array([[[-5.26756048e-06,  1.67742632e-02, -1.20154992e-02,
          3.78093757e-02, -3.26074734e-02, -2.06794031e-02,
         -3.73188145e-02, -2.42195968e-02,  4.26889770e-02,
         -2.93627623e-02],
        [-5.26756048e-06,  1.67742632e-02, -1.20154992e-02,
          3.78093757e-02, -3.26074734e-02, -2.06794031e-02,
         -3.73188145e-02, -2.42195968e-02,  4.26889770e-02,
         -2.93627623e-02],
        [-5.26756048e-06,  1.67742632e-02, -1.20154992e-02,
          3.78093757e-02, -3.26074734e-02, -2.06794031e-02,
         -3.73188145e-02, -2.42195968e-02,  4.26889770e-02,
         -2.93627623e-02],
        [-5.26756048e-06,  1.67742632e-02, -1.20154992e-02,
          3.78093757e-02, -3.26074734e-02, -2.06794031e-02,
         -3.73188145e-02, -2.42195968e-02,  4.26889770e-02,
         -2.93627623e-02],
        [-9.06217098e-03, -9.45527479e-03,  5.28198481e-03,
         -4.45024855e-02, -4.78453562e-03, -1.73988715e-02,
         -7.55983591e-03, -3.18970829e-02,  1.965165

In [36]:
embedded_docs[0]

array([   0,    0,    0,    0, 3015, 3836, 5472, 6520], dtype=int32)

In [40]:
type(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


numpy.ndarray

In [ ]:
model.save('embedding.h5')